name: video_to_frame_color_image
description: "Using Flutter and Rust to convert a video to an image made up of columns of the average color of each interval frame."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  rust_lib_video_to_frame_color_image:
    path: rust_builder
  flutter_rust_bridge: 2.0.0-dev.28
  get: ^4.6.6
  file_picker: ^8.0.0+1
  path_provider: ^2.1.2
  freezed_annotation: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  integration_test:
    sdk: flutter
  freezed: ^2.4.7
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
