[package]
name = "rust_lib_video_to_frame_color_image"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = "=2.0.0-dev.28"
image = "0.25.0"
anyhow = "1.0"
