// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.28.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Generate the image of size [pixel_width] * video time in seconds x [height] from
/// the video at [path] based on the frames at each [interval] seconds.
void generateImage(
        {required String path,
        required int interval,
        required int pixelWidth,
        required int height,
        dynamic hint}) =>
    RustLib.instance.api.generateImage(
        path: path,
        interval: interval,
        pixelWidth: pixelWidth,
        height: height,
        hint: hint);

/// This function is only used in calls from the Dart code.
///
/// The helper function was needed due to an issue with &String and
/// &str parameters.
Future<int> getVideoSecondsHelper({required String path, dynamic hint}) =>
    RustLib.instance.api.getVideoSecondsHelper(path: path, hint: hint);
